{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    android-tools
    audacity
    bambu-studio
    baobab
    bibata-cursors
    binwalk
    comaps
    davinci-resolve-studio
    deno
    espeak
    exiftool
    famistudio
    feather
    ffmpeg-full
    file
    fira-code
    gimp3
    gnome-calculator
    gnome-characters
    gnome-logs
    gnome-system-monitor
    gparted
    handbrake
    heroic
    imagemagick
    inkscape
    insomnia
    inter
    iosevka-bin
    keybase-gui
    krita
    languagetool
    libreoffice-fresh
    loupe
    lucida-downloader
    magic-wormhole-rs
    nautilus
    nodejs
    ocr-a
    olympus
    onlyoffice-desktopeditors
    parsec-bin
    parted
    pinta
    prettier
    prismlauncher
    prusa-slicer
    python314
    quodlibet-full
    reaper
    signal-desktop-bin
    slack
    snapshot
    sparrow
    sqlitebrowser
    superTuxKart
    tlrc
    tor
    tor-browser
    trezor-suite
    tutanota-desktop
    ungoogled-chromium
    unstable.telegram-desktop
    usbutils
    yubikey-manager
  ];
}
